import { NextRequest, NextResponse } from 'next/server'
import JSZip from 'jszip'
import { db } from '@/lib/db'
import { verifyToken, getTokenFromHeaders } from '@/lib/auth'

async function getAuthenticatedUserId(headers: Headers): Promise<string | null> {
  const token = getTokenFromHeaders(headers)
  if (!token) return null
  return verifyToken(token)
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const userId = await getAuthenticatedUserId(request.headers)
    if (!userId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { id: projectId } = await params

    const project = await db.project.findUnique({
      where: { id: projectId, userId },
      include: { files: true },
    })

    if (!project) {
      return NextResponse.json(
        { success: false, error: 'Project not found' },
        { status: 404 }
      )
    }

    if (project.files.length === 0) {
      return NextResponse.json(
        { success: false, error: 'No files to export' },
        { status: 400 }
      )
    }

    // Create ZIP archive
    const zip = new JSZip()

    // Add each project file to the ZIP
    for (const file of project.files) {
      zip.file(file.path, file.content)
    }

    // Add a README with project info
    const readme = `# ${project.name}

${project.description || ''}

## Project Info

- **Framework**: ${project.framework}
- **Status**: ${project.status}
- **Files**: ${project.files.length}
- **Created**: ${project.createdAt}
- **Last Updated**: ${project.updatedAt}

Generated by BuilderAI
`
    zip.file('README.md', readme)

    // Generate ZIP buffer
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' })

    // Sanitize project name for filename
    const safeName = project.name.replace(/[^a-zA-Z0-9-_]/g, '-').toLowerCase()

    return new Response(zipBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${safeName}.zip"`,
        'Content-Length': zipBuffer.length.toString(),
      },
    })
  } catch (error) {
    console.error('Export project error:', error)
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    )
  }
}
